# KB stack
version: '3.8'
volumes:
  db:
  killbill:
services:
  killbill:
    image: killbill/killbill:0.22.0
    ports:
      - "8080:8080"
      - "8000:8000"
      - "12345:12345"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
    volumes:
      - type: volume
        source: killbill
        target: /var/lib
    restart: unless-stopped
    tmpfs: /tmp
    depends_on: 
      - db
    deploy:
      replicas: 2
  kaui:
    image: killbill/kaui:latest
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
      - KAUI_KILLBILL_API_KEY=bob
      - KAUI_KILLBILL_API_SECRET=lazar
    volumes:
      - "/kaui:/var/lib"
    restart: unless-stopped
    depends_on: 
      - killbill
    deploy:
      replicas: 1
  db:
    image: killbill/mariadb:0.20
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
    deploy:
      replicas: 1
